// Package treegen writes internal/vm's tree_operand.go: the tree tier's
// nodes for an operator whose operands are a local, an upvalue or a number
// constant, which read them in place rather than calling a tree for them.
//
// A node is a closure, and a closure called for an operand is an indirect
// call that most operands -- a local, a constant -- do not need. Each node
// written here is one operator over one pairing of operand kinds, so that
// none of them asks at run time which it is; there are too many to keep by
// hand alike.
package treegen

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

// An operand kind, and how a node reads one.
type kind byte

const (
	local   kind = 'L' // c.locals[k]
	upvalue kind = 'U' // the closure's upvalue k
	number  kind = 'N' // a number known when the tree is built
	tree    kind = 'T' // any other entry, a tree to call
)

// test is the condition on a tentry that it is of the kind.
func (k kind) test(e string) string {
	switch k {
	case local:
		return e + ".local"
	case upvalue:
		return e + ".upvalue"
	case number:
		return e + ".number"
	}
	return "!" + e + ".local && !" + e + ".upvalue && !" + e + ".number"
}

// capture is what the node captures of a tentry of the kind.
func (k kind) capture(e string) string {
	switch k {
	case local, upvalue:
		return e + ".k"
	case number:
		return e + ".n"
	}
	return e + ".tree()"
}

// read is the node's read of the operand it captured as v.
func (k kind) read(v string) string {
	switch k {
	case local:
		return "c.locals[" + v + "]"
	case upvalue:
		return "*c.cl.upvalues[" + v + "].slot"
	case number:
		return v
	}
	return v + "(c)"
}

type pair struct{ x, y kind }

type op struct{ name, expr string }

// Generate returns the source of tree_operand.go.
func Generate() ([]byte, error) {
	var b bytes.Buffer
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }
	w("// Code generated by internal/vm/internal/treegen; DO NOT EDIT.")
	w("")
	w("package vm")
	w("")
	w(`import "github.com/go-quickjs/go-quickjs/internal/bytecode"`)

	// Arithmetic. An upvalue is read through its tree: what an arithmetic
	// loop reads is its own locals.
	w("")
	w("// arithOperands is an arithmetic operator over two entries, reading a local")
	w("// or a number in place, or nil where there is no node for the pairing.")
	w("func arithOperands(op bytecode.Op, x, y tentry, pc int) tval {")
	w("	switch {")
	arith := []op{{"OpAdd", "+"}, {"OpSub", "-"}, {"OpMul", "*"}, {"OpDiv", "/"}}
	asTree := func(k kind, e string) string {
		if k == tree {
			return "!" + e + ".local && !" + e + ".number"
		}
		return k.test(e)
	}
	for _, p := range []pair{{local, tree}, {tree, local}, {local, local}, {tree, number}, {local, number}, {number, tree}, {number, local}} {
		w("	case %s && %s:", asTree(p.x, "x"), asTree(p.y, "y"))
		w("		x, y := %s, %s", p.x.capture("x"), p.y.capture("y"))
		w("		switch op {")
		for _, o := range arith {
			w("		case bytecode.%s:", o.name)
			w("			return func(c *tctx) Value {")
			// Each operand is read in a statement of its own: the order
			// Go evaluates a multiple assignment's index expressions and
			// calls in is not the order they are written in.
			w("				a := %s", p.x.read("x"))
			w("				b := %s", p.y.read("y"))
			w("				if %s {", numberTests(p))
			w("					return Float(a.num %s b.num)", o.expr)
			w("				}")
			w("				return c.arithSlow(op, a, b, pc)")
			w("			}")
		}
		w("		}")
	}
	w("	}")
	w("	return nil")
	w("}")

	// Comparisons ending a block.
	w("")
	w("// cmpJump ends a block with a comparison and a forward jump where it is")
	w("// false: the comparison is the block's end rather than a tree the end")
	w("// calls, and its operands are read in place where they can be. It is nil")
	w("// where there is no node for the operator or the pairing.")
	w("func cmpJump(op bytecode.Op, x, y tentry, pc, taken, fall int) tnext {")
	w("	switch {")
	cmp := []op{{"OpLt", "<"}, {"OpLe", "<="}, {"OpGt", ">"}, {"OpGe", ">="}}
	for _, p := range []pair{{local, number}, {local, local}, {local, upvalue}, {local, tree}, {tree, number}, {tree, local}, {tree, upvalue}, {tree, tree}, {upvalue, local}, {number, local}} {
		w("	case %s && %s:", p.x.test("x"), p.y.test("y"))
		w("		x, y := %s, %s", p.x.capture("x"), p.y.capture("y"))
		w("		switch op {")
		for _, o := range cmp {
			w("		case bytecode.%s:", o.name)
			w("			return func(c *tctx) int {")
			w("				a := %s", p.x.read("x"))
			w("				b := %s", p.y.read("y"))
			w("				if %s {", numberTests(p))
			w("					if a.num %s b.num {", o.expr)
			w("						return fall")
			w("					}")
			w("					return taken")
			w("				}")
			w("				if c.compareSlow(op, a, b, pc) {")
			w("					return fall")
			w("				}")
			w("				return taken")
			w("			}")
		}
		w("		}")
	}
	w("	}")
	w("	return nil")
	w("}")

	// Bitwise operators over a local and a constant.
	w("")
	w("// bitwiseImmOperand is a bitwise operator over an entry and an integer")
	w("// constant, reading a local in place.")
	w("func bitwiseImmOperand(op bytecode.Op, x tentry, k int32, pc int) tval {")
	w("	if !x.local {")
	w("		return bitwiseImmNode(op, x.tree(), k, pc)")
	w("	}")
	w("	j, kv, n := x.k, Int32(k), uint32(k)&31")
	w("	switch op {")
	for _, o := range []op{
		{"OpBitAnd", "Int32(toInt32(a.num) & k)"},
		{"OpBitOr", "Int32(toInt32(a.num) | k)"},
		{"OpBitXor", "Int32(toInt32(a.num) ^ k)"},
		{"OpShl", "Int32(toInt32(a.num) << n)"},
		{"OpShr", "Int32(toInt32(a.num) >> n)"},
		{"OpUShr", "Uint32(uint32(toInt32(a.num)) >> n)"},
	} {
		w("	case bytecode.%s:", o.name)
		w("		return func(c *tctx) Value {")
		w("			if a := c.locals[j]; a.IsNumber() {")
		w("				return %s", o.expr)
		w("			} else {")
		w("				return c.bitwiseSlow(op, a, kv, pc)")
		w("			}")
		w("		}")
	}
	w("	}")
	w("	return bitwiseImmNode(op, x.tree(), k, pc)")
	w("}")

	return format.Source(b.Bytes())
}

// numberTests is the test that a node's operands are numbers, leaving out a
// number constant's, which is one.
func numberTests(p pair) string {
	var t []string
	if p.x != number {
		t = append(t, "a.IsNumber()")
	}
	if p.y != number {
		t = append(t, "b.IsNumber()")
	}
	return strings.Join(t, " && ")
}
