// Command winzonegen writes the Windows time-zone table the icu package
// carries.
//
// Windows names its zones its own way -- "Eastern Standard Time" rather than
// America/New_York -- and ECMA-402 requires the name the database uses, so a
// host running on Windows needs the mapping between them. CLDR publishes it as
// supplemental/windowsZones.json, which is vendored beside this command.
//
// Usage:
//
//	go run ./internal/icu/internal/winzonegen > internal/icu/windowszones.go
//
// The mapping is territory-aware because ICU's is: "Central Europe Standard
// Time" is Europe/Budapest in general but Europe/Prague in Czechia, and a host
// that ignored the territory would name the zone differently than the ICU this
// package is held against.
package main

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

//go:embed windowsZones.json
var windowsZones []byte

// resource is the shape of the CLDR file: a list of mappings, each naming a
// Windows identifier, a territory, and the database zones it stands for.
type resource struct {
	Supplemental struct {
		Version struct {
			CLDR string `json:"_cldrVersion"`
		} `json:"version"`
		WindowsZones struct {
			MapTimezones []struct {
				MapZone struct {
					Other     string `json:"_other"`
					Type      string `json:"_type"`
					Territory string `json:"_territory"`
				} `json:"mapZone"`
			} `json:"mapTimezones"`
		} `json:"windowsZones"`
	} `json:"supplemental"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "winzonegen:", err)
		os.Exit(1)
	}
}

func run() error {
	var data resource
	if err := json.Unmarshal(windowsZones, &data); err != nil {
		return fmt.Errorf("reading windowsZones.json: %w", err)
	}

	// The default for an identifier is its territory 001 row; the rest are the
	// territories that name a different zone than the default does. A row may
	// list several zones, the first of which is the one ICU answers with.
	defaults := map[string]string{}
	territories := map[string]string{}
	for _, entry := range data.Supplemental.WindowsZones.MapTimezones {
		zone := entry.MapZone
		first := zone.Type
		if at := strings.IndexByte(first, ' '); at >= 0 {
			first = first[:at]
		}
		if first == "" {
			continue
		}
		if zone.Territory == "001" {
			defaults[zone.Other] = first
			continue
		}
		territories[zone.Other+"\x00"+zone.Territory] = first
	}
	if len(defaults) == 0 {
		return fmt.Errorf("no territory 001 rows found")
	}

	// A territory row that names the same zone as the default carries no
	// information, so it is left out rather than doubling the table.
	for key, zone := range territories {
		identifier := key[:strings.IndexByte(key, '\x00')]
		if defaults[identifier] == zone {
			delete(territories, key)
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by winzonegen; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// Source: CLDR %s supplemental/windowsZones.json\n",
		data.Supplemental.Version.CLDR)
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "//\tgo run ./internal/icu/internal/winzonegen > internal/icu/windowszones.go\n\n")
	fmt.Fprintf(&b, "package icu\n\n")

	fmt.Fprintf(&b, "// windowsZoneDefaults is the zone each Windows identifier stands for when\n")
	fmt.Fprintf(&b, "// the territory is unknown or names no zone of its own: CLDR's 001 row.\n")
	fmt.Fprintf(&b, "var windowsZoneDefaults = map[string]string{\n")
	for _, key := range sorted(defaults) {
		fmt.Fprintf(&b, "\t%q: %q,\n", key, defaults[key])
	}
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "// windowsZoneTerritories is the zone an identifier stands for in one\n")
	fmt.Fprintf(&b, "// territory, where that differs from the default. The key is the identifier\n")
	fmt.Fprintf(&b, "// and the territory with a NUL between them, neither of which contains one.\n")
	fmt.Fprintf(&b, "var windowsZoneTerritories = map[string]string{\n")
	for _, key := range sorted(territories) {
		fmt.Fprintf(&b, "\t%q: %q,\n", key, territories[key])
	}
	fmt.Fprintf(&b, "}\n")

	_, err := os.Stdout.WriteString(b.String())
	return err
}

func sorted(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
