// Code generated by internal/asciigen from exec.go; DO NOT EDIT.

package regexp

import (
	"unicode/utf16"
	"unicode/utf8"
)

type inputASCII struct {
	units   []byte
	unicode bool
}

func (in *inputASCII) length() int {
	return len(in.units)
}

func (in *inputASCII) at(i int) (rune, int) {
	if i < 0 || i >= len(in.units) {
		return -1, 0
	}
	c := rune(in.units[i])
	if in.unicode && utf16.IsSurrogate(c) && i+1 < len(in.units) {
		if combined := utf16.DecodeRune(c, rune(in.units[i+1])); combined != utf8.RuneError {
			return combined, 2
		}
	}
	return c, 1
}

func (in *inputASCII) before(i int) (rune, int) {
	if i <= 0 {
		return -1, 0
	}
	c := rune(in.units[i-1])
	if in.unicode && utf16.IsSurrogate(c) && i >= 2 {
		if combined := utf16.DecodeRune(rune(in.units[i-2]), c); combined != utf8.RuneError {
			return combined, 2
		}
	}
	return c, 1
}

type matcherASCII struct {
	prog       *program
	in         *inputASCII
	input      inputASCII
	caps       []int
	trail      []capWrite
	stack      []frame
	counters   []int
	emptyMarks []int
	steps      int
	check      func() error
	busy       bool
}

func (m *matcherASCII) search(re *Regexp, dst []int, start int, sticky bool) ([]int, error) {
	in := m.in
	first := re.prog.first
	lit, litAt := re.prog.lit, -1
	if re.prog.anchored {
		if start != 0 {
			return nil, nil
		}
		sticky = true
	}
	if sticky || in.unicode {
		lit = nil
	}
	m.reset()
	for pos := start; pos <= in.length(); {
		if lit != nil {
			if litAt < pos+lit.minOff {
				if litAt = indexUnitsASCII(in.units, lit.units, pos+lit.minOff); litAt < 0 {
					return nil, nil
				}
			}
			pos = max(pos, litAt-lit.maxOff)
		}
		if first != nil && !in.unicode && !sticky {
			units := in.units
			for pos < len(units) && !first.admits(uint16(units[pos])) {
				pos++
			}
			if pos >= len(units) {
				return nil, nil
			}
			if lit != nil && litAt < pos+lit.minOff {
				continue
			}
		} else if first != nil {
			if pos >= len(in.units) || !first.admits(uint16(in.units[pos])) {
				if pos >= len(in.units) || sticky {
					return nil, nil
				}
				_, w := in.at(pos)
				if w == 0 {
					w = 1
				}
				pos += w
				continue
			}
		}
		ok, err := m.run(re.prog.code, pos)
		if err != nil {
			return nil, err
		}
		if ok {
			return append(dst[:0], m.caps...), nil
		}
		if len(m.trail) != 0 {
			m.undoCaps(0)
		}
		if sticky {
			return nil, nil
		}
		if !in.unicode {
			pos++
			continue
		}
		_, w := in.at(pos)
		if w == 0 {
			w = 1
		}
		pos += w
	}
	return nil, nil
}

func (m *matcherASCII) reset() {
	for i := range m.caps {
		m.caps[i] = -1
	}
	for i := range m.counters {
		m.counters[i] = 0
	}
	for i := range m.emptyMarks {
		m.emptyMarks[i] = -1
	}
	m.trail = m.trail[:0]
	m.stack = m.stack[:0]
}

func (m *matcherASCII) run(code []instr, pos int) (bool, error) {
	pc := 0
	units, unicode := m.in.units, m.in.unicode
	for {
		m.steps++
		if m.check != nil {
			if m.steps%checkInterval == 0 {
				if err := m.check(); err != nil {
					return false, err
				}
			}
		} else if m.steps > maxSteps {
			return false, ErrComplexity
		}
		in := &code[pc]
		switch in.op {
		case opChar:
			if !in.rev && uint(pos) < uint(len(units)) {
				if u := units[pos]; !unicode || !utf16.IsSurrogate(rune(u)) {
					if rune(u) != in.r {
						goto backtrack
					}
					pos++
					pc++
					break
				}
			}
			r, w := m.read(in.rev, pos)
			if r != in.r {
				goto backtrack
			}
			pos = m.advance(in.rev, pos, w)
			pc++
		case opCharFold:
			r, w := m.read(in.rev, pos)
			if r < 0 || canonical(r, m.prog.unicodeFold) != in.r {
				goto backtrack
			}
			pos = m.advance(in.rev, pos, w)
			pc++
		case opClass:
			if !in.rev && uint(pos) < uint(len(units)) {
				if u := units[pos]; u < 128 {
					if m.prog.asciiClasses[in.arg][u>>6]&(1<<(u&63)) == 0 {
						goto backtrack
					}
					pos++
					pc++
					break
				}
			}
			r, w := m.read(in.rev, pos)
			if r < 0 {
				goto backtrack
			}
			if r < 128 {
				if m.prog.asciiClasses[in.arg][r>>6]&(1<<(r&63)) == 0 {
					goto backtrack
				}
			} else if !m.prog.classes[in.arg].contains(r, m.prog.unicodeFold) {
				goto backtrack
			}
			pos = m.advance(in.rev, pos, w)
			pc++
		case opAny:
			r, w := m.read(in.rev, pos)
			if r < 0 {
				goto backtrack
			}
			pos = m.advance(in.rev, pos, w)
			pc++
		case opAnyNotNL:
			r, w := m.read(in.rev, pos)
			if r < 0 || isLineTerminator(r) {
				goto backtrack
			}
			pos = m.advance(in.rev, pos, w)
			pc++
		case opSplit:
			m.stack = append(m.stack, frame{pc: int32(in.arg2), pos: int32(pos), capsLen: int32(len(m.trail)), counterIdx: -1})
			pc = in.arg
		case opJmp:
			pc = in.arg
		case opSave:
			m.setCap(in.arg, pos)
			pc++
		case opMatch:
			return true, nil
		case opAssertStart:
			if pos == 0 {
				pc++
				break
			}
			if in.arg != 0 {
				if r, _ := m.in.before(pos); isLineTerminator(r) {
					pc++
					break
				}
			}
			goto backtrack
		case opAssertEnd:
			if pos == m.in.length() {
				pc++
				break
			}
			if in.arg != 0 {
				if r, _ := m.in.at(pos); isLineTerminator(r) {
					pc++
					break
				}
			}
			goto backtrack
		case opWordBoundary, opNotWordBoundary:
			prev, _ := m.in.before(pos)
			next, _ := m.in.at(pos)
			fold := in.arg != 0
			atBoundary := isWordChar(prev, fold) != isWordChar(next, fold)
			if atBoundary == (in.op == opWordBoundary) {
				pc++
				break
			}
			goto backtrack
		case opBackref, opBackrefFold:
			g := in.arg
			if in.arg2 != 0 {
				for _, k := range m.prog.refSets[in.arg2-1] {
					if m.caps[2*k] >= 0 {
						g = k
						break
					}
				}
			}
			if 2*g+1 >= len(m.caps) {
				pc++
				break
			}
			start, end := m.caps[2*g], m.caps[2*g+1]
			if start < 0 || end < 0 {
				pc++
				break
			}
			n := end - start
			at := pos
			if in.rev {
				at = pos - n
				if at < 0 {
					goto backtrack
				}
			} else if pos+n > m.in.length() {
				goto backtrack
			}
			if !m.compareRange(start, at, n, in.op == opBackrefFold) {
				goto backtrack
			}
			pos = at
			if !in.rev {
				pos = pos + n
			}
			pc++
		case opLook:
			ok, err := m.runLook(in.arg, pos)
			if err != nil {
				return false, err
			}
			if !ok {
				goto backtrack
			}
			pc++
		case opCounterInit:
			m.counters[in.arg] = 0
			pc++
		case opCounterInc:
			min, max := in.arg2, int(in.r)
			cur := m.counters[in.arg]
			if max >= 0 && cur >= max {
				pc = m.exitOfCounterLoop(code, pc)
				break
			}
			m.counters[in.arg] = cur + 1
			m.push(frame{pc: -1, counterIdx: int32(in.arg), counterVal: int32(cur), pos: int32(pos), capsLen: int32(len(m.trail)), emptyIdx: -1})
			if cur < min {
				pc += 2
				break
			}
			pc++
		case opClearCaps:
			for g := in.arg; g <= in.arg2; g++ {
				if m.caps[2*g] >= 0 || m.caps[2*g+1] >= 0 {
					m.setCap(2*g, -1)
					m.setCap(2*g+1, -1)
				}
			}
			pc++
		case opGreedy:
			item := code[pc+1]
			units := m.in.units
			end := pos
			switch item.op {
			case opClass:
				ascii := &m.prog.asciiClasses[item.arg]
				for end < len(units) {
					if u := units[end]; u < 128 {
						if ascii[u>>6]&(1<<(u&63)) == 0 {
							break
						}
					} else if !m.prog.classes[item.arg].contains(rune(u), m.prog.unicodeFold) {
						break
					}
					end++
				}
			case opChar:
				for end < len(units) && rune(units[end]) == item.r {
					end++
				}
			case opAny:
				end = len(units)
			default:
				for end < len(units) && m.unitMatches(item, uint16(units[end])) {
					end++
				}
			}
			m.steps += end - pos
			if end-pos < in.arg {
				goto backtrack
			}
			if lo := pos + in.arg; end > lo {
				m.push(frame{pc: int32(pc + 2), pos: int32(end), capsLen: int32(len(m.trail)), counterIdx: greedyFrame, counterVal: int32(lo)})
			}
			pos = end
			pc += 2
		case opEmptyCheck:
			if in.arg2 == 0 {
				m.push(frame{pc: -1, emptyIdx: int32(in.arg), emptyVal: int32(m.emptyMarks[in.arg]), pos: int32(pos), capsLen: int32(len(m.trail)), counterIdx: -1})
				m.emptyMarks[in.arg] = pos
				pc++
				break
			}
			if m.emptyMarks[in.arg] == pos {
				goto backtrack
			}
			pc++
		default:
			goto backtrack
		}
		continue
	backtrack:
		for {
			if len(m.stack) == 0 {
				return false, nil
			}
			f := m.stack[len(m.stack)-1]
			m.stack = m.stack[:len(m.stack)-1]
			if len(m.trail) > int(f.capsLen) {
				m.undoCaps(int(f.capsLen))
			}
			if f.counterIdx == greedyFrame {
				p := f.pos - 1
				if p > f.counterVal {
					f.pos = p
					m.stack = append(m.stack, f)
				}
				pc, pos = int(f.pc), int(p)
				break
			}
			if f.counterIdx >= 0 && f.pc == -1 {
				m.counters[f.counterIdx] = int(f.counterVal)
				continue
			}
			if f.emptyIdx >= 0 && f.pc == -1 {
				m.emptyMarks[f.emptyIdx] = int(f.emptyVal)
				continue
			}
			pc, pos = int(f.pc), int(f.pos)
			break
		}
	}
}

func (m *matcherASCII) exitOfCounterLoop(code []instr, pc int) int {
	split := code[pc+1]
	if split.op != opSplit {
		return pc + 1
	}
	if split.arg == pc+2 {
		return split.arg2
	}
	return split.arg
}

func (m *matcherASCII) push(f frame) {
	if f.counterIdx == 0 && f.pc != -1 {
		f.counterIdx = -1
	}
	m.stack = append(m.stack, f)
}

func (m *matcherASCII) unitMatches(in instr, u uint16) bool {
	r := rune(u)
	switch in.op {
	case opChar:
		return r == in.r
	case opCharFold:
		return canonical(r, m.prog.unicodeFold) == in.r
	case opClass:
		if r < 128 {
			return m.prog.asciiClasses[in.arg][r>>6]&(1<<(r&63)) != 0
		}
		return m.prog.classes[in.arg].contains(r, m.prog.unicodeFold)
	case opAny:
		return true
	default:
		return !isLineTerminator(r)
	}
}

func (m *matcherASCII) setCap(slot, pos int) {
	m.trail = append(m.trail, capWrite{slot: slot, prev: m.caps[slot]})
	m.caps[slot] = pos
}

func (m *matcherASCII) undoCaps(n int) {
	for len(m.trail) > n {
		w := m.trail[len(m.trail)-1]
		m.trail = m.trail[:len(m.trail)-1]
		m.caps[w.slot] = w.prev
	}
}

func (m *matcherASCII) read(rev bool, pos int) (rune, int) {
	if rev {
		return m.in.before(pos)
	}
	return m.in.at(pos)
}

func (m *matcherASCII) advance(rev bool, pos, w int) int {
	if rev {
		return pos - w
	}
	return pos + w
}

func (m *matcherASCII) compareRange(a, b, n int, fold bool) bool {
	for i := 0; i < n; i++ {
		x, y := rune(m.in.units[a+i]), rune(m.in.units[b+i])
		if x == y {
			continue
		}
		if !fold || canonical(x, m.prog.unicodeFold) != canonical(y, m.prog.unicodeFold) {
			return false
		}
	}
	return true
}

func (m *matcherASCII) runLook(idx, pos int) (bool, error) {
	look := m.prog.looks[idx]
	base := len(m.trail)
	sub := &matcherASCII{prog: m.prog, in: m.in, caps: m.caps, trail: m.trail, counters: make([]int, m.prog.counters), emptyMarks: make([]int, m.prog.emptyChecks), steps: m.steps, check: m.check}
	for i := range sub.emptyMarks {
		sub.emptyMarks[i] = -1
	}
	ok, err := sub.run(look.code, pos)
	m.steps = sub.steps
	if err != nil {
		m.trail = sub.trail
		return false, err
	}
	if !ok || look.negate {
		sub.undoCaps(base)
	}
	m.trail = sub.trail
	if look.negate {
		return !ok, nil
	}
	return ok, nil
}
