// Package asciigen makes the regexp matcher over the bytes of an ASCII string
// from the matcher over UTF-16 code units, so that the two are the same code
// and the one the engine uses is left exactly as written.
package asciigen

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"sort"
	"strconv"
)

// Generate makes exec_ascii.go's text from the matcher in path, exec.go: its
// input and matcher types and their methods, renamed, with the input's code
// units made bytes.
func Generate(path string) ([]byte, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil, err
	}
	rename := map[string]string{
		"input":      "inputASCII",
		"matcher":    "matcherASCII",
		"indexUnits": "indexUnitsASCII",
	}
	recvIs := func(fd *ast.FuncDecl, names ...string) bool {
		if fd.Recv == nil || len(fd.Recv.List) != 1 {
			return false
		}
		star, ok := fd.Recv.List[0].Type.(*ast.StarExpr)
		if !ok {
			return false
		}
		id, ok := star.X.(*ast.Ident)
		if !ok {
			return false
		}
		for _, n := range names {
			if id.Name == n {
				return true
			}
		}
		return false
	}
	var decls []ast.Decl
	for _, d := range file.Decls {
		switch d := d.(type) {
		case *ast.GenDecl:
			if d.Tok != token.TYPE {
				continue
			}
			for _, spec := range d.Specs {
				ts := spec.(*ast.TypeSpec)
				if ts.Name.Name == "input" || ts.Name.Name == "matcher" {
					decls = append(decls, &ast.GenDecl{Tok: token.TYPE, Specs: []ast.Spec{ts}})
				}
			}
		case *ast.FuncDecl:
			if recvIs(d, "input", "matcher") {
				d.Doc = nil
				decls = append(decls, d)
			}
		}
	}
	// A field, a selected name and a literal's key keep their names: only the
	// types and the function are renamed, not the matcher's field called input.
	kept := map[*ast.Ident]bool{}
	for _, d := range decls {
		ast.Inspect(d, func(n ast.Node) bool {
			switch n := n.(type) {
			case *ast.Field:
				for _, id := range n.Names {
					kept[id] = true
				}
			case *ast.SelectorExpr:
				kept[n.Sel] = true
			case *ast.KeyValueExpr:
				if id, ok := n.Key.(*ast.Ident); ok {
					kept[id] = true
				}
			}
			return true
		})
	}
	imports := map[string]bool{}
	for _, d := range decls {
		ast.Inspect(d, func(n ast.Node) bool {
			switch n := n.(type) {
			case *ast.Ident:
				if to, ok := rename[n.Name]; ok && !kept[n] {
					n.Name = to
				}
			case *ast.TypeSpec:
				// The input's code units are bytes.
				if n.Name.Name == "input" || n.Name.Name == "inputASCII" {
					for _, f := range n.Type.(*ast.StructType).Fields.List {
						if len(f.Names) == 1 && f.Names[0].Name == "units" {
							f.Type = &ast.ArrayType{Elt: ast.NewIdent("byte")}
						}
					}
				}
			case *ast.SelectorExpr:
				if pkg, ok := n.X.(*ast.Ident); ok {
					switch pkg.Name {
					case "utf16", "utf8", "errors", "sync":
						imports[pkg.Name] = true
					}
				}
			}
			return true
		})
	}
	paths := map[string]string{"utf16": "unicode/utf16", "utf8": "unicode/utf8", "errors": "errors", "sync": "sync"}
	var names []string
	for name := range imports {
		names = append(names, paths[name])
	}
	sort.Strings(names)

	var b bytes.Buffer
	b.WriteString("// Code generated by internal/asciigen from exec.go; DO NOT EDIT.\n\n")
	b.WriteString("package regexp\n\n")
	if len(names) > 0 {
		b.WriteString("import (\n")
		for _, p := range names {
			b.WriteString("\t" + strconv.Quote(p) + "\n")
		}
		b.WriteString(")\n")
	}
	for _, d := range decls {
		b.WriteString("\n")
		if err := format.Node(&b, token.NewFileSet(), d); err != nil {
			return nil, err
		}
		b.WriteString("\n")
	}
	return format.Source(b.Bytes())
}
