// Code generated by internal/vm/internal/treegen; DO NOT EDIT.

package vm

import "github.com/go-quickjs/go-quickjs/internal/bytecode"

// arithOperands is an arithmetic operator over two entries, reading a local
// or a number in place, or nil where there is no node for the pairing.
func arithOperands(op bytecode.Op, x, y tentry, pc int) tval {
	slow := arithSlow(op, pc)
	switch {
	case x.local && !y.local && !y.number:
		x, y := x.k, y.v
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num + b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpSub:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num - b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpMul:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num * b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpDiv:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num / b.num)
				}
				return slow(c, a, b)
			}
		}
	case !x.local && !x.number && y.local:
		x, y := x.v, y.k
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) Value {
				a := x(c)
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num + b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpSub:
			return func(c *tctx) Value {
				a := x(c)
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num - b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpMul:
			return func(c *tctx) Value {
				a := x(c)
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num * b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpDiv:
			return func(c *tctx) Value {
				a := x(c)
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num / b.num)
				}
				return slow(c, a, b)
			}
		}
	case x.local && y.local:
		x, y := x.k, y.k
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num + b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpSub:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num - b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpMul:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num * b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpDiv:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num / b.num)
				}
				return slow(c, a, b)
			}
		}
	case !x.local && !x.number && y.number:
		x, y := x.v, y.n
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) Value {
				a := x(c)
				b := y
				if a.IsNumber() {
					return Float(a.num + b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpSub:
			return func(c *tctx) Value {
				a := x(c)
				b := y
				if a.IsNumber() {
					return Float(a.num - b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpMul:
			return func(c *tctx) Value {
				a := x(c)
				b := y
				if a.IsNumber() {
					return Float(a.num * b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpDiv:
			return func(c *tctx) Value {
				a := x(c)
				b := y
				if a.IsNumber() {
					return Float(a.num / b.num)
				}
				return slow(c, a, b)
			}
		}
	case x.local && y.number:
		x, y := x.k, y.n
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := y
				if a.IsNumber() {
					return Float(a.num + b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpSub:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := y
				if a.IsNumber() {
					return Float(a.num - b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpMul:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := y
				if a.IsNumber() {
					return Float(a.num * b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpDiv:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := y
				if a.IsNumber() {
					return Float(a.num / b.num)
				}
				return slow(c, a, b)
			}
		}
	case x.number && !y.local && !y.number:
		x, y := x.n, y.v
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) Value {
				a := x
				b := y(c)
				if b.IsNumber() {
					return Float(a.num + b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpSub:
			return func(c *tctx) Value {
				a := x
				b := y(c)
				if b.IsNumber() {
					return Float(a.num - b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpMul:
			return func(c *tctx) Value {
				a := x
				b := y(c)
				if b.IsNumber() {
					return Float(a.num * b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpDiv:
			return func(c *tctx) Value {
				a := x
				b := y(c)
				if b.IsNumber() {
					return Float(a.num / b.num)
				}
				return slow(c, a, b)
			}
		}
	case x.number && y.local:
		x, y := x.n, y.k
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) Value {
				a := x
				b := c.locals[y]
				if b.IsNumber() {
					return Float(a.num + b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpSub:
			return func(c *tctx) Value {
				a := x
				b := c.locals[y]
				if b.IsNumber() {
					return Float(a.num - b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpMul:
			return func(c *tctx) Value {
				a := x
				b := c.locals[y]
				if b.IsNumber() {
					return Float(a.num * b.num)
				}
				return slow(c, a, b)
			}
		case bytecode.OpDiv:
			return func(c *tctx) Value {
				a := x
				b := c.locals[y]
				if b.IsNumber() {
					return Float(a.num / b.num)
				}
				return slow(c, a, b)
			}
		}
	}
	return nil
}

// cmpJump ends a block with a comparison and a forward jump where it is
// false: the comparison is the block's end rather than a tree the end
// calls, and its operands are read in place where they can be. It is nil
// where there is no node for the operator or the pairing.
func cmpJump(op bytecode.Op, x, y tentry, pc, taken, fall int) tnext {
	switch {
	case x.local && y.number:
		x, y := x.k, y.n
		switch op {
		case bytecode.OpLt:
			return func(c *tctx) int {
				a := c.locals[x]
				b := y
				if a.IsNumber() {
					if a.num < b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpLe:
			return func(c *tctx) int {
				a := c.locals[x]
				b := y
				if a.IsNumber() {
					if a.num <= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGt:
			return func(c *tctx) int {
				a := c.locals[x]
				b := y
				if a.IsNumber() {
					if a.num > b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGe:
			return func(c *tctx) int {
				a := c.locals[x]
				b := y
				if a.IsNumber() {
					if a.num >= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		}
	case x.local && y.local:
		x, y := x.k, y.k
		switch op {
		case bytecode.OpLt:
			return func(c *tctx) int {
				a := c.locals[x]
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num < b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpLe:
			return func(c *tctx) int {
				a := c.locals[x]
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num <= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGt:
			return func(c *tctx) int {
				a := c.locals[x]
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num > b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGe:
			return func(c *tctx) int {
				a := c.locals[x]
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num >= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		}
	case x.local && y.upvalue:
		x, y := x.k, y.k
		switch op {
		case bytecode.OpLt:
			return func(c *tctx) int {
				a := c.locals[x]
				b := *c.cl.upvalues[y].slot
				if a.IsNumber() && b.IsNumber() {
					if a.num < b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpLe:
			return func(c *tctx) int {
				a := c.locals[x]
				b := *c.cl.upvalues[y].slot
				if a.IsNumber() && b.IsNumber() {
					if a.num <= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGt:
			return func(c *tctx) int {
				a := c.locals[x]
				b := *c.cl.upvalues[y].slot
				if a.IsNumber() && b.IsNumber() {
					if a.num > b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGe:
			return func(c *tctx) int {
				a := c.locals[x]
				b := *c.cl.upvalues[y].slot
				if a.IsNumber() && b.IsNumber() {
					if a.num >= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		}
	case x.local && !y.local && !y.upvalue && !y.number:
		x, y := x.k, y.v
		switch op {
		case bytecode.OpLt:
			return func(c *tctx) int {
				a := c.locals[x]
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					if a.num < b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpLe:
			return func(c *tctx) int {
				a := c.locals[x]
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					if a.num <= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGt:
			return func(c *tctx) int {
				a := c.locals[x]
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					if a.num > b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGe:
			return func(c *tctx) int {
				a := c.locals[x]
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					if a.num >= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		}
	case !x.local && !x.upvalue && !x.number && y.number:
		x, y := x.v, y.n
		switch op {
		case bytecode.OpLt:
			return func(c *tctx) int {
				a := x(c)
				b := y
				if a.IsNumber() {
					if a.num < b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpLe:
			return func(c *tctx) int {
				a := x(c)
				b := y
				if a.IsNumber() {
					if a.num <= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGt:
			return func(c *tctx) int {
				a := x(c)
				b := y
				if a.IsNumber() {
					if a.num > b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGe:
			return func(c *tctx) int {
				a := x(c)
				b := y
				if a.IsNumber() {
					if a.num >= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		}
	case !x.local && !x.upvalue && !x.number && y.local:
		x, y := x.v, y.k
		switch op {
		case bytecode.OpLt:
			return func(c *tctx) int {
				a := x(c)
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num < b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpLe:
			return func(c *tctx) int {
				a := x(c)
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num <= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGt:
			return func(c *tctx) int {
				a := x(c)
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num > b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGe:
			return func(c *tctx) int {
				a := x(c)
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num >= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		}
	case !x.local && !x.upvalue && !x.number && y.upvalue:
		x, y := x.v, y.k
		switch op {
		case bytecode.OpLt:
			return func(c *tctx) int {
				a := x(c)
				b := *c.cl.upvalues[y].slot
				if a.IsNumber() && b.IsNumber() {
					if a.num < b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpLe:
			return func(c *tctx) int {
				a := x(c)
				b := *c.cl.upvalues[y].slot
				if a.IsNumber() && b.IsNumber() {
					if a.num <= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGt:
			return func(c *tctx) int {
				a := x(c)
				b := *c.cl.upvalues[y].slot
				if a.IsNumber() && b.IsNumber() {
					if a.num > b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGe:
			return func(c *tctx) int {
				a := x(c)
				b := *c.cl.upvalues[y].slot
				if a.IsNumber() && b.IsNumber() {
					if a.num >= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		}
	case !x.local && !x.upvalue && !x.number && !y.local && !y.upvalue && !y.number:
		x, y := x.v, y.v
		switch op {
		case bytecode.OpLt:
			return func(c *tctx) int {
				a := x(c)
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					if a.num < b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpLe:
			return func(c *tctx) int {
				a := x(c)
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					if a.num <= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGt:
			return func(c *tctx) int {
				a := x(c)
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					if a.num > b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGe:
			return func(c *tctx) int {
				a := x(c)
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					if a.num >= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		}
	case x.upvalue && y.local:
		x, y := x.k, y.k
		switch op {
		case bytecode.OpLt:
			return func(c *tctx) int {
				a := *c.cl.upvalues[x].slot
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num < b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpLe:
			return func(c *tctx) int {
				a := *c.cl.upvalues[x].slot
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num <= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGt:
			return func(c *tctx) int {
				a := *c.cl.upvalues[x].slot
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num > b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGe:
			return func(c *tctx) int {
				a := *c.cl.upvalues[x].slot
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num >= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		}
	case x.number && y.local:
		x, y := x.n, y.k
		switch op {
		case bytecode.OpLt:
			return func(c *tctx) int {
				a := x
				b := c.locals[y]
				if b.IsNumber() {
					if a.num < b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpLe:
			return func(c *tctx) int {
				a := x
				b := c.locals[y]
				if b.IsNumber() {
					if a.num <= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGt:
			return func(c *tctx) int {
				a := x
				b := c.locals[y]
				if b.IsNumber() {
					if a.num > b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGe:
			return func(c *tctx) int {
				a := x
				b := c.locals[y]
				if b.IsNumber() {
					if a.num >= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		}
	}
	return nil
}

// bitwiseImmOperand is a bitwise operator over an entry and an integer
// constant, reading a local in place.
func bitwiseImmOperand(op bytecode.Op, x tentry, k int32, pc int) tval {
	if !x.local {
		return bitwiseImmNode(op, x.v, k, pc)
	}
	j, kv, n := x.k, Int32(k), uint32(k)&31
	switch op {
	case bytecode.OpBitAnd:
		return func(c *tctx) Value {
			if a := c.locals[j]; a.IsNumber() {
				return Int32(toInt32(a.num) & k)
			} else {
				return c.bitwiseSlow(op, a, kv, pc)
			}
		}
	case bytecode.OpBitOr:
		return func(c *tctx) Value {
			if a := c.locals[j]; a.IsNumber() {
				return Int32(toInt32(a.num) | k)
			} else {
				return c.bitwiseSlow(op, a, kv, pc)
			}
		}
	case bytecode.OpBitXor:
		return func(c *tctx) Value {
			if a := c.locals[j]; a.IsNumber() {
				return Int32(toInt32(a.num) ^ k)
			} else {
				return c.bitwiseSlow(op, a, kv, pc)
			}
		}
	case bytecode.OpShl:
		return func(c *tctx) Value {
			if a := c.locals[j]; a.IsNumber() {
				return Int32(toInt32(a.num) << n)
			} else {
				return c.bitwiseSlow(op, a, kv, pc)
			}
		}
	case bytecode.OpShr:
		return func(c *tctx) Value {
			if a := c.locals[j]; a.IsNumber() {
				return Int32(toInt32(a.num) >> n)
			} else {
				return c.bitwiseSlow(op, a, kv, pc)
			}
		}
	case bytecode.OpUShr:
		return func(c *tctx) Value {
			if a := c.locals[j]; a.IsNumber() {
				return Uint32(uint32(toInt32(a.num)) >> n)
			} else {
				return c.bitwiseSlow(op, a, kv, pc)
			}
		}
	}
	return bitwiseImmNode(op, x.v, k, pc)
}
