// Code generated by internal/vm/internal/treegen; DO NOT EDIT.

package vm

import "github.com/go-quickjs/go-quickjs/internal/bytecode"

// arithOperands is an arithmetic operator over two entries, reading a local
// or a number in place, or nil where there is no node for the pairing.
func arithOperands(op bytecode.Op, x, y tentry, pc int) tval {
	switch {
	case x.local && !y.local && !y.number:
		x, y := x.k, y.tree()
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num + b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpSub:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num - b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpMul:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num * b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpDiv:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num / b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		}
	case !x.local && !x.number && y.local:
		x, y := x.tree(), y.k
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) Value {
				a := x(c)
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num + b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpSub:
			return func(c *tctx) Value {
				a := x(c)
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num - b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpMul:
			return func(c *tctx) Value {
				a := x(c)
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num * b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpDiv:
			return func(c *tctx) Value {
				a := x(c)
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num / b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		}
	case x.local && y.local:
		x, y := x.k, y.k
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num + b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpSub:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num - b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpMul:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num * b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpDiv:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					return Float(a.num / b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		}
	case !x.local && !x.number && y.number:
		x, y := x.tree(), y.n
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) Value {
				a := x(c)
				b := y
				if a.IsNumber() {
					return Float(a.num + b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpSub:
			return func(c *tctx) Value {
				a := x(c)
				b := y
				if a.IsNumber() {
					return Float(a.num - b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpMul:
			return func(c *tctx) Value {
				a := x(c)
				b := y
				if a.IsNumber() {
					return Float(a.num * b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpDiv:
			return func(c *tctx) Value {
				a := x(c)
				b := y
				if a.IsNumber() {
					return Float(a.num / b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		}
	case x.local && y.number:
		x, y := x.k, y.n
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := y
				if a.IsNumber() {
					return Float(a.num + b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpSub:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := y
				if a.IsNumber() {
					return Float(a.num - b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpMul:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := y
				if a.IsNumber() {
					return Float(a.num * b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpDiv:
			return func(c *tctx) Value {
				a := c.locals[x]
				b := y
				if a.IsNumber() {
					return Float(a.num / b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		}
	case x.number && !y.local && !y.number:
		x, y := x.n, y.tree()
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) Value {
				a := x
				b := y(c)
				if b.IsNumber() {
					return Float(a.num + b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpSub:
			return func(c *tctx) Value {
				a := x
				b := y(c)
				if b.IsNumber() {
					return Float(a.num - b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpMul:
			return func(c *tctx) Value {
				a := x
				b := y(c)
				if b.IsNumber() {
					return Float(a.num * b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpDiv:
			return func(c *tctx) Value {
				a := x
				b := y(c)
				if b.IsNumber() {
					return Float(a.num / b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		}
	case x.number && y.local:
		x, y := x.n, y.k
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) Value {
				a := x
				b := c.locals[y]
				if b.IsNumber() {
					return Float(a.num + b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpSub:
			return func(c *tctx) Value {
				a := x
				b := c.locals[y]
				if b.IsNumber() {
					return Float(a.num - b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpMul:
			return func(c *tctx) Value {
				a := x
				b := c.locals[y]
				if b.IsNumber() {
					return Float(a.num * b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		case bytecode.OpDiv:
			return func(c *tctx) Value {
				a := x
				b := c.locals[y]
				if b.IsNumber() {
					return Float(a.num / b.num)
				}
				return c.arithSlow(op, a, b, pc)
			}
		}
	}
	return nil
}

// cmpJump ends a block with a comparison and a forward jump where it is
// false: the comparison is the block's end rather than a tree the end
// calls, and its operands are read in place where they can be. It is nil
// where there is no node for the operator or the pairing.
func cmpJump(op bytecode.Op, x, y tentry, pc, taken, fall int) tnext {
	switch {
	case x.local && y.number:
		x, y := x.k, y.n
		switch op {
		case bytecode.OpLt:
			return func(c *tctx) int {
				a := c.locals[x]
				b := y
				if a.IsNumber() {
					if a.num < b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpLe:
			return func(c *tctx) int {
				a := c.locals[x]
				b := y
				if a.IsNumber() {
					if a.num <= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGt:
			return func(c *tctx) int {
				a := c.locals[x]
				b := y
				if a.IsNumber() {
					if a.num > b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGe:
			return func(c *tctx) int {
				a := c.locals[x]
				b := y
				if a.IsNumber() {
					if a.num >= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		}
	case x.local && y.local:
		x, y := x.k, y.k
		switch op {
		case bytecode.OpLt:
			return func(c *tctx) int {
				a := c.locals[x]
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num < b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpLe:
			return func(c *tctx) int {
				a := c.locals[x]
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num <= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGt:
			return func(c *tctx) int {
				a := c.locals[x]
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num > b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGe:
			return func(c *tctx) int {
				a := c.locals[x]
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num >= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		}
	case x.local && y.upvalue:
		x, y := x.k, y.k
		switch op {
		case bytecode.OpLt:
			return func(c *tctx) int {
				a := c.locals[x]
				b := *c.cl.upvalues[y].slot
				if a.IsNumber() && b.IsNumber() {
					if a.num < b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpLe:
			return func(c *tctx) int {
				a := c.locals[x]
				b := *c.cl.upvalues[y].slot
				if a.IsNumber() && b.IsNumber() {
					if a.num <= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGt:
			return func(c *tctx) int {
				a := c.locals[x]
				b := *c.cl.upvalues[y].slot
				if a.IsNumber() && b.IsNumber() {
					if a.num > b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGe:
			return func(c *tctx) int {
				a := c.locals[x]
				b := *c.cl.upvalues[y].slot
				if a.IsNumber() && b.IsNumber() {
					if a.num >= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		}
	case x.local && !y.local && !y.upvalue && !y.number:
		x, y := x.k, y.tree()
		switch op {
		case bytecode.OpLt:
			return func(c *tctx) int {
				a := c.locals[x]
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					if a.num < b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpLe:
			return func(c *tctx) int {
				a := c.locals[x]
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					if a.num <= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGt:
			return func(c *tctx) int {
				a := c.locals[x]
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					if a.num > b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGe:
			return func(c *tctx) int {
				a := c.locals[x]
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					if a.num >= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		}
	case !x.local && !x.upvalue && !x.number && y.number:
		x, y := x.tree(), y.n
		switch op {
		case bytecode.OpLt:
			return func(c *tctx) int {
				a := x(c)
				b := y
				if a.IsNumber() {
					if a.num < b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpLe:
			return func(c *tctx) int {
				a := x(c)
				b := y
				if a.IsNumber() {
					if a.num <= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGt:
			return func(c *tctx) int {
				a := x(c)
				b := y
				if a.IsNumber() {
					if a.num > b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGe:
			return func(c *tctx) int {
				a := x(c)
				b := y
				if a.IsNumber() {
					if a.num >= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		}
	case !x.local && !x.upvalue && !x.number && y.local:
		x, y := x.tree(), y.k
		switch op {
		case bytecode.OpLt:
			return func(c *tctx) int {
				a := x(c)
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num < b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpLe:
			return func(c *tctx) int {
				a := x(c)
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num <= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGt:
			return func(c *tctx) int {
				a := x(c)
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num > b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGe:
			return func(c *tctx) int {
				a := x(c)
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num >= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		}
	case !x.local && !x.upvalue && !x.number && y.upvalue:
		x, y := x.tree(), y.k
		switch op {
		case bytecode.OpLt:
			return func(c *tctx) int {
				a := x(c)
				b := *c.cl.upvalues[y].slot
				if a.IsNumber() && b.IsNumber() {
					if a.num < b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpLe:
			return func(c *tctx) int {
				a := x(c)
				b := *c.cl.upvalues[y].slot
				if a.IsNumber() && b.IsNumber() {
					if a.num <= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGt:
			return func(c *tctx) int {
				a := x(c)
				b := *c.cl.upvalues[y].slot
				if a.IsNumber() && b.IsNumber() {
					if a.num > b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGe:
			return func(c *tctx) int {
				a := x(c)
				b := *c.cl.upvalues[y].slot
				if a.IsNumber() && b.IsNumber() {
					if a.num >= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		}
	case !x.local && !x.upvalue && !x.number && !y.local && !y.upvalue && !y.number:
		x, y := x.tree(), y.tree()
		switch op {
		case bytecode.OpLt:
			return func(c *tctx) int {
				a := x(c)
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					if a.num < b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpLe:
			return func(c *tctx) int {
				a := x(c)
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					if a.num <= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGt:
			return func(c *tctx) int {
				a := x(c)
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					if a.num > b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGe:
			return func(c *tctx) int {
				a := x(c)
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					if a.num >= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		}
	case x.upvalue && y.local:
		x, y := x.k, y.k
		switch op {
		case bytecode.OpLt:
			return func(c *tctx) int {
				a := *c.cl.upvalues[x].slot
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num < b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpLe:
			return func(c *tctx) int {
				a := *c.cl.upvalues[x].slot
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num <= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGt:
			return func(c *tctx) int {
				a := *c.cl.upvalues[x].slot
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num > b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGe:
			return func(c *tctx) int {
				a := *c.cl.upvalues[x].slot
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					if a.num >= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		}
	case x.number && y.local:
		x, y := x.n, y.k
		switch op {
		case bytecode.OpLt:
			return func(c *tctx) int {
				a := x
				b := c.locals[y]
				if b.IsNumber() {
					if a.num < b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpLe:
			return func(c *tctx) int {
				a := x
				b := c.locals[y]
				if b.IsNumber() {
					if a.num <= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGt:
			return func(c *tctx) int {
				a := x
				b := c.locals[y]
				if b.IsNumber() {
					if a.num > b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		case bytecode.OpGe:
			return func(c *tctx) int {
				a := x
				b := c.locals[y]
				if b.IsNumber() {
					if a.num >= b.num {
						return fall
					}
					return taken
				}
				if c.compareSlow(op, a, b, pc) {
					return fall
				}
				return taken
			}
		}
	}
	return nil
}

// bitwiseImmOperand is a bitwise operator over an entry and an integer
// constant, reading a local in place.
func bitwiseImmOperand(op bytecode.Op, x tentry, k int32, pc int) tval {
	if !x.local {
		return bitwiseImmNode(op, x.tree(), k, pc)
	}
	j, kv, n := x.k, Int32(k), uint32(k)&31
	switch op {
	case bytecode.OpBitAnd:
		return func(c *tctx) Value {
			if a := c.locals[j]; a.IsNumber() {
				return Int32(toInt32(a.num) & k)
			} else {
				return c.bitwiseSlow(op, a, kv, pc)
			}
		}
	case bytecode.OpBitOr:
		return func(c *tctx) Value {
			if a := c.locals[j]; a.IsNumber() {
				return Int32(toInt32(a.num) | k)
			} else {
				return c.bitwiseSlow(op, a, kv, pc)
			}
		}
	case bytecode.OpBitXor:
		return func(c *tctx) Value {
			if a := c.locals[j]; a.IsNumber() {
				return Int32(toInt32(a.num) ^ k)
			} else {
				return c.bitwiseSlow(op, a, kv, pc)
			}
		}
	case bytecode.OpShl:
		return func(c *tctx) Value {
			if a := c.locals[j]; a.IsNumber() {
				return Int32(toInt32(a.num) << n)
			} else {
				return c.bitwiseSlow(op, a, kv, pc)
			}
		}
	case bytecode.OpShr:
		return func(c *tctx) Value {
			if a := c.locals[j]; a.IsNumber() {
				return Int32(toInt32(a.num) >> n)
			} else {
				return c.bitwiseSlow(op, a, kv, pc)
			}
		}
	case bytecode.OpUShr:
		return func(c *tctx) Value {
			if a := c.locals[j]; a.IsNumber() {
				return Uint32(uint32(toInt32(a.num)) >> n)
			} else {
				return c.bitwiseSlow(op, a, kv, pc)
			}
		}
	}
	return bitwiseImmNode(op, x.tree(), k, pc)
}

// storeArith is local k = e as one statement, for an entry that is an
// arithmetic or bitwise node over operands it read in place, or nil where
// there is no statement for it. The statement does what the node and the
// store did, in their order, without calling the node.
func storeArith(k uint32, e tentry) tstmt {
	a := e.arith
	if a == nil {
		return nil
	}
	if a.imm {
		return bitwiseImmStore(a.op, k, a.x, a.k, a.pc)
	}
	return arithStore(a.op, k, a.x, a.y, a.pc)
}

// arithStore is local k = x op y for an arithmetic operator, over the
// pairings arithOperands reads in place and two trees otherwise.
func arithStore(op bytecode.Op, k uint32, x, y tentry, pc int) tstmt {
	switch {
	case x.local && !y.local && !y.number:
		x, y := x.k, y.tree()
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) {
				a := c.locals[x]
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					c.locals[k] = Float(a.num + b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpSub:
			return func(c *tctx) {
				a := c.locals[x]
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					c.locals[k] = Float(a.num - b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpMul:
			return func(c *tctx) {
				a := c.locals[x]
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					c.locals[k] = Float(a.num * b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpDiv:
			return func(c *tctx) {
				a := c.locals[x]
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					c.locals[k] = Float(a.num / b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		}
	case !x.local && !x.number && y.local:
		x, y := x.tree(), y.k
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) {
				a := x(c)
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					c.locals[k] = Float(a.num + b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpSub:
			return func(c *tctx) {
				a := x(c)
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					c.locals[k] = Float(a.num - b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpMul:
			return func(c *tctx) {
				a := x(c)
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					c.locals[k] = Float(a.num * b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpDiv:
			return func(c *tctx) {
				a := x(c)
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					c.locals[k] = Float(a.num / b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		}
	case x.local && y.local:
		x, y := x.k, y.k
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) {
				a := c.locals[x]
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					c.locals[k] = Float(a.num + b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpSub:
			return func(c *tctx) {
				a := c.locals[x]
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					c.locals[k] = Float(a.num - b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpMul:
			return func(c *tctx) {
				a := c.locals[x]
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					c.locals[k] = Float(a.num * b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpDiv:
			return func(c *tctx) {
				a := c.locals[x]
				b := c.locals[y]
				if a.IsNumber() && b.IsNumber() {
					c.locals[k] = Float(a.num / b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		}
	case !x.local && !x.number && y.number:
		x, y := x.tree(), y.n
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) {
				a := x(c)
				b := y
				if a.IsNumber() {
					c.locals[k] = Float(a.num + b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpSub:
			return func(c *tctx) {
				a := x(c)
				b := y
				if a.IsNumber() {
					c.locals[k] = Float(a.num - b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpMul:
			return func(c *tctx) {
				a := x(c)
				b := y
				if a.IsNumber() {
					c.locals[k] = Float(a.num * b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpDiv:
			return func(c *tctx) {
				a := x(c)
				b := y
				if a.IsNumber() {
					c.locals[k] = Float(a.num / b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		}
	case x.local && y.number:
		x, y := x.k, y.n
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) {
				a := c.locals[x]
				b := y
				if a.IsNumber() {
					c.locals[k] = Float(a.num + b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpSub:
			return func(c *tctx) {
				a := c.locals[x]
				b := y
				if a.IsNumber() {
					c.locals[k] = Float(a.num - b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpMul:
			return func(c *tctx) {
				a := c.locals[x]
				b := y
				if a.IsNumber() {
					c.locals[k] = Float(a.num * b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpDiv:
			return func(c *tctx) {
				a := c.locals[x]
				b := y
				if a.IsNumber() {
					c.locals[k] = Float(a.num / b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		}
	case x.number && !y.local && !y.number:
		x, y := x.n, y.tree()
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) {
				a := x
				b := y(c)
				if b.IsNumber() {
					c.locals[k] = Float(a.num + b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpSub:
			return func(c *tctx) {
				a := x
				b := y(c)
				if b.IsNumber() {
					c.locals[k] = Float(a.num - b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpMul:
			return func(c *tctx) {
				a := x
				b := y(c)
				if b.IsNumber() {
					c.locals[k] = Float(a.num * b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpDiv:
			return func(c *tctx) {
				a := x
				b := y(c)
				if b.IsNumber() {
					c.locals[k] = Float(a.num / b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		}
	case x.number && y.local:
		x, y := x.n, y.k
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) {
				a := x
				b := c.locals[y]
				if b.IsNumber() {
					c.locals[k] = Float(a.num + b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpSub:
			return func(c *tctx) {
				a := x
				b := c.locals[y]
				if b.IsNumber() {
					c.locals[k] = Float(a.num - b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpMul:
			return func(c *tctx) {
				a := x
				b := c.locals[y]
				if b.IsNumber() {
					c.locals[k] = Float(a.num * b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpDiv:
			return func(c *tctx) {
				a := x
				b := c.locals[y]
				if b.IsNumber() {
					c.locals[k] = Float(a.num / b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		}
	default:
		x, y := x.tree(), y.tree()
		switch op {
		case bytecode.OpAdd:
			return func(c *tctx) {
				a := x(c)
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					c.locals[k] = Float(a.num + b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpSub:
			return func(c *tctx) {
				a := x(c)
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					c.locals[k] = Float(a.num - b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpMul:
			return func(c *tctx) {
				a := x(c)
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					c.locals[k] = Float(a.num * b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		case bytecode.OpDiv:
			return func(c *tctx) {
				a := x(c)
				b := y(c)
				if a.IsNumber() && b.IsNumber() {
					c.locals[k] = Float(a.num / b.num)
				} else {
					c.locals[k] = c.arithSlow(op, a, b, pc)
				}
			}
		}
	}
	return nil
}

// bitwiseImmStore is local k = x op n for a bitwise operator and an
// integer constant.
func bitwiseImmStore(op bytecode.Op, k uint32, x tentry, n int32, pc int) tstmt {
	kv, s := Int32(n), uint32(n)&31
	if x.local {
		x := x.k
		switch op {
		case bytecode.OpBitAnd:
			return func(c *tctx) {
				if a := c.locals[x]; a.IsNumber() {
					c.locals[k] = Int32(toInt32(a.num) & n)
				} else {
					c.locals[k] = c.bitwiseSlow(op, a, kv, pc)
				}
			}
		case bytecode.OpBitOr:
			return func(c *tctx) {
				if a := c.locals[x]; a.IsNumber() {
					c.locals[k] = Int32(toInt32(a.num) | n)
				} else {
					c.locals[k] = c.bitwiseSlow(op, a, kv, pc)
				}
			}
		case bytecode.OpBitXor:
			return func(c *tctx) {
				if a := c.locals[x]; a.IsNumber() {
					c.locals[k] = Int32(toInt32(a.num) ^ n)
				} else {
					c.locals[k] = c.bitwiseSlow(op, a, kv, pc)
				}
			}
		case bytecode.OpShl:
			return func(c *tctx) {
				if a := c.locals[x]; a.IsNumber() {
					c.locals[k] = Int32(toInt32(a.num) << s)
				} else {
					c.locals[k] = c.bitwiseSlow(op, a, kv, pc)
				}
			}
		case bytecode.OpShr:
			return func(c *tctx) {
				if a := c.locals[x]; a.IsNumber() {
					c.locals[k] = Int32(toInt32(a.num) >> s)
				} else {
					c.locals[k] = c.bitwiseSlow(op, a, kv, pc)
				}
			}
		case bytecode.OpUShr:
			return func(c *tctx) {
				if a := c.locals[x]; a.IsNumber() {
					c.locals[k] = Uint32(uint32(toInt32(a.num)) >> s)
				} else {
					c.locals[k] = c.bitwiseSlow(op, a, kv, pc)
				}
			}
		}
	}
	{
		x := x.tree()
		switch op {
		case bytecode.OpBitAnd:
			return func(c *tctx) {
				if a := x(c); a.IsNumber() {
					c.locals[k] = Int32(toInt32(a.num) & n)
				} else {
					c.locals[k] = c.bitwiseSlow(op, a, kv, pc)
				}
			}
		case bytecode.OpBitOr:
			return func(c *tctx) {
				if a := x(c); a.IsNumber() {
					c.locals[k] = Int32(toInt32(a.num) | n)
				} else {
					c.locals[k] = c.bitwiseSlow(op, a, kv, pc)
				}
			}
		case bytecode.OpBitXor:
			return func(c *tctx) {
				if a := x(c); a.IsNumber() {
					c.locals[k] = Int32(toInt32(a.num) ^ n)
				} else {
					c.locals[k] = c.bitwiseSlow(op, a, kv, pc)
				}
			}
		case bytecode.OpShl:
			return func(c *tctx) {
				if a := x(c); a.IsNumber() {
					c.locals[k] = Int32(toInt32(a.num) << s)
				} else {
					c.locals[k] = c.bitwiseSlow(op, a, kv, pc)
				}
			}
		case bytecode.OpShr:
			return func(c *tctx) {
				if a := x(c); a.IsNumber() {
					c.locals[k] = Int32(toInt32(a.num) >> s)
				} else {
					c.locals[k] = c.bitwiseSlow(op, a, kv, pc)
				}
			}
		case bytecode.OpUShr:
			return func(c *tctx) {
				if a := x(c); a.IsNumber() {
					c.locals[k] = Uint32(uint32(toInt32(a.num)) >> s)
				} else {
					c.locals[k] = c.bitwiseSlow(op, a, kv, pc)
				}
			}
		}
	}
	return nil
}
