// Code generated by cldrgen; DO NOT EDIT.

// Package intldata carries what things are called in every language
// this engine knows: the languages, the regions, the scripts, the
// currencies and the parts of a date.
//
// The main quickjs package imports this package so Intl.DisplayNames answers
// in the language it was asked in. It remains public for compatibility with
// programs that imported it explicitly:
//
//	import _ "github.com/go-quickjs/go-quickjs/intldata"
//
// The names remain in a separately compressed asset and are decoded one
// locale at a time on first use.
package intldata

import (
	_ "embed"
	"github.com/go-quickjs/go-quickjs/internal/icu"
)

//go:embed tables.bin
var packedTables []byte

func init() {
	icu.RegisterDisplayNames(packed)
}

var packed = packedTables[0:876283]
