// Code generated by cldrgen; DO NOT EDIT.

// Package intldata carries what things are called in every language
// this engine knows: the languages, the regions, the scripts, the
// currencies and the parts of a date.
//
// Import it for its effect alone, and Intl.DisplayNames answers in the
// language it was asked in rather than in English:
//
//	import _ "github.com/go-quickjs/go-quickjs/intldata"
//
// The names are kept in this optional compressed asset so a program
// that never opens a language picker does not carry the name of every
// country in every language.
package intldata

import (
	_ "embed"
	"github.com/go-quickjs/go-quickjs/internal/icu"
)

//go:embed tables.bin
var packedTables []byte

func init() {
	icu.RegisterDisplayNames(packed)
}

var packed = packedTables[0:876283]
